"""Replay re-derives book_hash from recorded depth streams (contract §H; S3).

S3 is the replay-stability invariant: a depth row persisted with a
``derived_book_hash`` MUST re-derive that EXACT hash on replay, byte-for-byte,
from the SAME flat field names persistence wrote (``recorder.event_row.from_row``).
The hash is a deterministic pure function of the canonical ladder (``book_hash``),
so it is identical across runs, hosts, vendor-insertion order, and after a
reconnect (different ts/vendor_seq/epoch, unchanged book).

Golden-by-construction: ``replay_expected_hashes.json`` is GENERATED by running
``book_hash`` over ``mbp10_depth_sample.jsonl`` once (the first green run) and
pinned. Values are never hand-guessed; the test that generates it asserts the
re-derivation is self-consistent, and every other test pins against the file.

§N cases bound to replay (S3):
- re-derives expected book_hashes byte-for-byte (keyed (symbol, vendor_seq)).
- replay is idempotent (same input twice -> identical hashes).
- book_hash is order-independent (shuffled vendor level order -> same hash).
- canonical payload excludes provenance (ts/vendor_seq/epoch/ct do not move it).
- book_hash includes identity (different symbol/instrument_id -> different hash).
- zero-size + duplicate-price encodings of one book hash identically.
- a "300.0" size and a "300" size produce the SAME book_hash (MAJOR 3).
- a float reaching the payload raises via the serializer (S2/S3).
- persisted depth row replays to the same hash via from_row (BLOCKER 2 e2e).
- truncated tail dropped (not fatal); corrupt midline / tampered hash fatal.
"""
import json
import tempfile
import unittest
from decimal import Decimal
from pathlib import Path

from agent.journal import JournalCorruption
from recorder.book_hash import BOOK_HASH_VERSION, book_hash, canonical_book_payload
from recorder.book_state import BookSnapshot, EquityBookState
from recorder.event import DepthEvent, DepthLevel, Provenance, parse
from recorder.persistence import EventWriter, replay_stream
from recorder.replay import (
    ReplayHashMismatch,
    ReplayResult,
    assert_matches_expected,
    derive_book_hashes,
    replay_book_hashes,
)
from recorder.status import make_data_quality_alert

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "databento"
DEPTH_FIXTURE = FIXTURES / "mbp10_depth_sample.jsonl"
EXPECTED_HASHES = FIXTURES / "replay_expected_hashes.json"

TS_RECV = "2026-06-09T13:30:00.000999Z"


def _load_jsonl(path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def _parse_record(record, *, reconnect_epoch=0):
    return parse(
        record,
        dataset=record["dataset"],
        schema=record["schema"],
        reconnect_epoch=reconnect_epoch,
        ts_recv_utc=TS_RECV,
    )


def _depth_events():
    return [_parse_record(rec) for rec in _load_jsonl(DEPTH_FIXTURE)]


class _Tmp(unittest.TestCase):
    """Fresh temp dir per test so the path-keyed journal seq registry (journal.py:70)
    does not bleed state across tests (mirrors test_persistence.py:_Tmp)."""

    def setUp(self):
        self._dir = tempfile.TemporaryDirectory()
        self.root = Path(self._dir.name)

    def tearDown(self):
        self._dir.cleanup()

    def _events_path(self):
        return self.root / "events.jsonl"


class TestReplayRederivesExpectedBookHashes(_Tmp):
    def test_replay_rederives_expected_book_hashes(self):
        # The fixture-driven derivation re-derives the pinned golden hashes byte-for-byte.
        result = derive_book_hashes(_depth_events())
        self.assertTrue(result.ok)
        self.assertIsNone(result.first_mismatch)
        # Golden-by-construction: pin against the committed expected-hashes file.
        assert_matches_expected(result, EXPECTED_HASHES)
        expected = json.loads(EXPECTED_HASHES.read_text(encoding="utf-8"))
        for entry in expected["hashes"]:
            # D5: map keyed (symbol, vendor_seq, occurrence); unique keys -> occurrence 0.
            key = (entry["symbol"], entry["vendor_seq"], 0)
            self.assertEqual(result.rederived_book_hashes[key], entry["book_hash"])

    def test_expected_hashes_file_shape_is_frozen(self):
        expected = json.loads(EXPECTED_HASHES.read_text(encoding="utf-8"))
        self.assertEqual(expected["v"], BOOK_HASH_VERSION)
        self.assertEqual(expected["book_hash_algo"], "row_hash(canonical_book_payload(snapshot))")
        keys = [(h["symbol"], h["vendor_seq"]) for h in expected["hashes"]]
        self.assertEqual(keys, [("AAPL", 2001), ("AAPL", 2002)])

    def test_replay_is_idempotent(self):
        first = derive_book_hashes(_depth_events())
        second = derive_book_hashes(_depth_events())
        self.assertEqual(first.rederived_book_hashes, second.rederived_book_hashes)


class TestBookHashDeterminism(_Tmp):
    def test_book_hash_is_order_independent(self):
        # Shuffling the vendor level order on a side must NOT change the hash.
        rec = _load_jsonl(DEPTH_FIXTURE)[0]
        shuffled = dict(rec)
        shuffled["bids"] = list(reversed(rec["bids"]))
        shuffled["asks"] = list(reversed(rec["asks"]))
        ev_a = _parse_record(rec)
        ev_b = _parse_record(shuffled)
        a = EquityBookState(ev_a.provenance.symbol, ev_a.provenance.instrument_id)
        a.apply(ev_a)
        b = EquityBookState(ev_b.provenance.symbol, ev_b.provenance.instrument_id)
        b.apply(ev_b)
        self.assertEqual(book_hash(a.snapshot()), book_hash(b.snapshot()))

    def test_canonical_payload_excludes_provenance(self):
        # ts / vendor_seq / reconnect_epoch / ct change but the payload does not.
        rec = _load_jsonl(DEPTH_FIXTURE)[0]
        ev0 = _parse_record(rec, reconnect_epoch=0)
        rec2 = dict(rec)
        rec2["vendor_seq"] = 999999
        rec2["ts_event"] = "2030-01-01T00:00:00.000000Z"
        ev1 = _parse_record(rec2, reconnect_epoch=7)
        s0 = EquityBookState("AAPL", 1001)
        s0.apply(ev0)
        s1 = EquityBookState("AAPL", 1001)
        s1.apply(ev1)
        self.assertEqual(canonical_book_payload(s0.snapshot()), canonical_book_payload(s1.snapshot()))
        self.assertEqual(book_hash(s0.snapshot()), book_hash(s1.snapshot()))

    def test_book_hash_includes_identity(self):
        rec = _load_jsonl(DEPTH_FIXTURE)[0]
        ev = _parse_record(rec)
        base = EquityBookState("AAPL", 1001)
        base.apply(ev)
        other_symbol = EquityBookState("MSFT", 1001)
        other_symbol.apply(_rebind(ev, symbol="MSFT", instrument_id=1001))
        other_id = EquityBookState("AAPL", 2002)
        other_id.apply(_rebind(ev, symbol="AAPL", instrument_id=2002))
        self.assertNotEqual(book_hash(base.snapshot()), book_hash(other_symbol.snapshot()))
        self.assertNotEqual(book_hash(base.snapshot()), book_hash(other_id.snapshot()))

    def test_zero_size_and_duplicate_price_normalized(self):
        # Fixture row 2001: a zero-size padding level is dropped and 201.1400 split
        # across two entries ("200"+"300") coalesces to "500" -> a single canonical book.
        ev = _depth_events()[0]
        state = EquityBookState("AAPL", 1001)
        state.apply(ev)
        payload = canonical_book_payload(state.snapshot())
        bids = payload["bids"]
        self.assertNotIn(["201.1500", "0"], bids)  # zero-size padding dropped
        self.assertIn(["201.1400", "500"], bids)    # split price coalesced
        # An equivalent book expressed without the padding/split hashes identically.
        equivalent = DepthEvent(
            provenance=ev.provenance,
            bids=(
                DepthLevel(px=Decimal("201.1500"), sz=Decimal("300"), ct=3),
                DepthLevel(px=Decimal("201.1400"), sz=Decimal("500"), ct=5),
            ),
            asks=ev.asks,
        )
        eq_state = EquityBookState("AAPL", 1001)
        eq_state.apply(equivalent)
        self.assertEqual(book_hash(state.snapshot()), book_hash(eq_state.snapshot()))

    def test_size_canonicalization_into_book_hash(self):
        # MAJOR 3: a "300.0" size and a "300" size, once PARSED (quantized to
        # SIZE_QUANTUM at parse, §B), produce the SAME book_hash.
        base = {
            "dataset": "<DEPTH_DATASET>", "schema": "mbp-10", "instrument_id": 1001,
            "symbol": "AAPL", "vendor_seq": 7001, "ts_event": "2026-06-09T13:30:00.500000Z",
            "asks": [["201.1600", "200", 1]],
        }
        ev_dotzero = _parse_record({**base, "bids": [["201.1500", "300.0", 1]]})
        ev_plain = _parse_record({**base, "bids": [["201.1500", "300", 1]]})
        a = EquityBookState("AAPL", 1001)
        a.apply(ev_dotzero)
        b = EquityBookState("AAPL", 1001)
        b.apply(ev_plain)
        self.assertEqual(book_hash(a.snapshot()), book_hash(b.snapshot()))

    def test_float_price_into_book_hash_raises(self):
        # A float reaching the canonical payload must fail loud via the serializer.
        bad = BookSnapshot(
            symbol="AAPL",
            instrument_id=1001,
            bids=(DepthLevel(px=1.23, sz=Decimal("100"), ct=1),),  # float px
            asks=(),
            crossed=False,
        )
        with self.assertRaises((ValueError, TypeError)):
            book_hash(bad)


class TestD5NullVendorSeqOrdinalKeying(_Tmp):
    """D5 (R2#5): per-row hash verification keyed by per-stream ORDINAL, not
    (symbol, vendor_seq). Two null-vendor_seq depth rows would collapse into ONE
    (symbol, None) map slot (last-write-wins) and MASK a wrong non-last row in the
    re-derived map that assert_matches_expected / reconcile join on. Each row MUST
    get its own verified slot.
    """

    def _ev(self, bid_px, *, ts):
        return DepthEvent(
            provenance=Provenance(
                dataset="<DEPTH_DATASET>", schema="mbp-10", instrument_id=1001,
                symbol="AAPL", vendor_seq=None, ts_event_utc=ts,
                ts_recv_utc=TS_RECV, reconnect_epoch=0,
            ),
            bids=(DepthLevel(px=Decimal(bid_px), sz=Decimal("300"), ct=1),),
            asks=(DepthLevel(px=Decimal("201.1600"), sz=Decimal("200"), ct=2),),
        )

    def test_two_null_seq_rows_each_get_own_slot(self):
        # Two DISTINCT books, both null vendor_seq, both persisted with CORRECT hashes.
        # The re-derived map must retain BOTH (one slot per row), not collapse to one.
        writer = EventWriter(self._events_path(), run_id="run-1")
        for bid_px, ts in (("201.1500", "2026-06-09T13:30:00.5Z"),
                           ("201.1400", "2026-06-09T13:30:01.5Z")):
            ev = self._ev(bid_px, ts=ts)
            state = EquityBookState("AAPL", 1001)
            state.apply(ev)
            writer.write_event(ev, derived_book_hash=book_hash(state.snapshot()))
        result = replay_book_hashes(self._events_path())
        self.assertTrue(result.ok)
        # Both distinct books survive in the map (no (symbol, None) last-write-wins collapse).
        self.assertEqual(len(result.rederived_book_hashes), 2)
        self.assertEqual(len(set(result.rederived_book_hashes.values())), 2)

    def test_nonlast_null_seq_wrong_hash_surfaced_in_map(self):
        # Row 0 (non-last) null-seq carries a WRONG derived_book_hash; row 1 null-seq
        # is correct. The wrong row must remain visible in the re-derived map (its own
        # slot), not be overwritten by the last null-seq row.
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev0 = self._ev("201.1500", ts="2026-06-09T13:30:00.5Z")
        ev1 = self._ev("201.1400", ts="2026-06-09T13:30:01.5Z")
        state1 = EquityBookState("AAPL", 1001)
        state1.apply(ev1)
        writer.write_event(ev0, derived_book_hash="00" * 32)  # wrong, non-last
        writer.write_event(ev1, derived_book_hash=book_hash(state1.snapshot()))
        result = replay_book_hashes(self._events_path())
        self.assertFalse(result.ok)
        self.assertEqual(result.first_mismatch["vendor_seq"], None)
        # The map keeps a slot for EACH null-seq row (no collapse to a single (AAPL,None)).
        self.assertEqual(len(result.rederived_book_hashes), 2)


class TestPersistedReplayRoundTrip(_Tmp):
    def test_persisted_depth_row_replays_to_same_hash(self):
        # BLOCKER 2 end-to-end: write_event(DepthEvent) with the recorder-computed
        # derived_book_hash, then replay.py via from_row re-derives the SAME hash.
        writer = EventWriter(self._events_path(), run_id="run-1")
        for ev in _depth_events():
            state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
            state.apply(ev)
            bh = book_hash(state.snapshot())
            writer.write_event(ev, derived_book_hash=bh)
        result = replay_book_hashes(self._events_path())
        self.assertTrue(result.ok)
        self.assertIsNone(result.first_mismatch)
        # The re-derived hash byte-matches the persisted derived_book_hash for every row.
        for ev in _depth_events():
            # D5: map keyed (symbol, vendor_seq, occurrence); fixture keys are unique -> 0.
            key = (ev.provenance.symbol, ev.provenance.vendor_seq, 0)
            state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
            state.apply(ev)
            self.assertEqual(result.rederived_book_hashes[key], book_hash(state.snapshot()))

    def test_persisted_replay_detects_mismatch(self):
        # If the persisted derived_book_hash does NOT match the re-derived hash,
        # replay reports it (never silently mutates) -> ok=False, first_mismatch set.
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        writer.write_event(ev, derived_book_hash="00" * 32)  # wrong on purpose
        result = replay_book_hashes(self._events_path())
        self.assertFalse(result.ok)
        self.assertIsNotNone(result.first_mismatch)
        self.assertEqual(result.first_mismatch["symbol"], "AAPL")
        self.assertEqual(result.first_mismatch["vendor_seq"], 2001)

    def test_nonlast_duplicate_key_mismatch_is_caught(self):
        # C2 (finding #6): two persisted rows share (symbol, vendor_seq); the NON-LAST
        # row carries a WRONG derived_book_hash. A dict keyed by (symbol, vendor_seq)
        # would last-write-win and mask it. Replay must verify EVERY row in ROW ORDER.
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
        state.apply(ev)
        good = book_hash(state.snapshot())
        # Row 1 (non-last): wrong hash for the SAME key. Row 2: correct hash, same key.
        writer.write_event(ev, derived_book_hash="00" * 32)
        writer.write_event(ev, derived_book_hash=good)
        result = replay_book_hashes(self._events_path())
        self.assertFalse(result.ok)
        self.assertIsNotNone(result.first_mismatch)
        self.assertEqual(result.first_mismatch["symbol"], "AAPL")
        self.assertEqual(result.first_mismatch["vendor_seq"], 2001)
        self.assertEqual(result.first_mismatch["recorded_hash"], "00" * 32)

    def test_replay_drops_truncated_tail_not_fatal(self):
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
        state.apply(ev)
        writer.write_event(ev, derived_book_hash=book_hash(state.snapshot()))
        path = self._events_path()
        # Append a truncated (no trailing newline) partial line: a crash mid-write.
        with open(path, "a", encoding="utf-8") as fh:
            fh.write('{"schema":"mbp-10","partial')
        result = replay_book_hashes(path)
        self.assertTrue(result.ok)
        self.assertEqual(len(result.rows), 1)

    def test_replay_corrupt_midline_is_fatal(self):
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
        state.apply(ev)
        writer.write_event(ev, derived_book_hash=book_hash(state.snapshot()))
        path = self._events_path()
        # A complete (newline-terminated) corrupt line is fatal (inherited from M0).
        with open(path, "a", encoding="utf-8") as fh:
            fh.write("not json at all\n")
        with self.assertRaises(JournalCorruption):
            replay_book_hashes(path)

    def test_replay_detects_tampered_hash(self):
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
        state.apply(ev)
        writer.write_event(ev, derived_book_hash=book_hash(state.snapshot()))
        path = self._events_path()
        line = json.loads(path.read_text(encoding="utf-8").splitlines()[0])
        line["instrument_id"] = 9999  # row hash no longer matches
        path.write_text(json.dumps(line) + "\n", encoding="utf-8")
        with self.assertRaises(JournalCorruption):
            replay_book_hashes(path)


class TestE2ReplaySkipsNonEventRows(_Tmp):
    """E2 (R3#2): replay/reconcile MUST SKIP non-event rows.

    When no alert_writer is injected, the recorder routes data_quality_alert rows
    (which have NO ``schema`` field) into the events stream. Before the fix,
    ``replay_book_hashes`` called ``from_row`` unconditionally on every row, so an
    alert row crashed the WHOLE replay with
    ``MalformedRecord('missing required flat field schema')``. The guard
    ``if 'schema' not in row: continue`` makes depth-hash verification apply only to
    schema-bearing event rows; the alert row is silently skipped.
    """

    def test_replay_skips_alert_rows_and_verifies_depth(self):
        # A stream mixing one valid depth row + one data_quality_alert row exactly as
        # make_data_quality_alert produces (no 'schema' field).
        writer = EventWriter(self._events_path(), run_id="run-1")
        ev = _depth_events()[0]
        state = EquityBookState(ev.provenance.symbol, ev.provenance.instrument_id)
        state.apply(ev)
        bh = book_hash(state.snapshot())
        writer.write_event(ev, derived_book_hash=bh)
        alert = make_data_quality_alert(
            cause="crossed_book", symbol="AAPL", detail="bid>=ask", reconnect_epoch=0
        )
        self.assertNotIn("schema", alert)  # the alert body carries no schema
        writer.record("data_quality_alert", alert)
        # Before the fix this raised MalformedRecord; now it replays cleanly and still
        # re-derives/verifies the depth row's book_hash.
        result = replay_book_hashes(self._events_path())
        self.assertTrue(result.ok)
        self.assertIsNone(result.first_mismatch)
        key = (ev.provenance.symbol, ev.provenance.vendor_seq, 0)
        self.assertEqual(result.rederived_book_hashes[key], bh)
        # The alert row contributes no book_hash slot (only the depth row does).
        self.assertEqual(len(result.rederived_book_hashes), 1)


class TestAssertMatchesExpected(_Tmp):
    def test_mismatch_against_expected_raises(self):
        result = derive_book_hashes(_depth_events())
        bad = self.root / "bad_expected.json"
        bad.write_text(
            json.dumps({
                "v": BOOK_HASH_VERSION,
                "book_hash_algo": "row_hash(canonical_book_payload(snapshot))",
                "hashes": [
                    {"symbol": "AAPL", "vendor_seq": 2001, "book_hash": "deadbeef" * 8},
                    {"symbol": "AAPL", "vendor_seq": 2002, "book_hash": "deadbeef" * 8},
                ],
            }),
            encoding="utf-8",
        )
        with self.assertRaises(ReplayHashMismatch):
            assert_matches_expected(result, bad)

    def test_result_is_replayresult_with_snapshots(self):
        result = derive_book_hashes(_depth_events())
        self.assertIsInstance(result, ReplayResult)
        self.assertIn("AAPL", result.final_snapshots)
        self.assertIsInstance(result.final_snapshots["AAPL"], BookSnapshot)


def _rebind(ev, *, symbol, instrument_id):
    """Return a copy of a DepthEvent with a different identity (for the identity test)."""
    prov = ev.provenance
    new_prov = Provenance(
        dataset=prov.dataset,
        schema=prov.schema,
        instrument_id=instrument_id,
        symbol=symbol,
        vendor_seq=prov.vendor_seq,
        ts_event_utc=prov.ts_event_utc,
        ts_recv_utc=prov.ts_recv_utc,
        reconnect_epoch=prov.reconnect_epoch,
    )
    return DepthEvent(provenance=new_prov, bids=ev.bids, asks=ev.asks)


if __name__ == "__main__":
    unittest.main()
